import './globals.css'
import { Poppins } from 'next/font/google'

//set up google font,use poppins.className to apply the poppins font to the body
const poppins=Poppins(
  {weight:['400','700'],
  subsets:['latin'],
}
)

export const metadata = {
  title: 'next app version 13',
  description: 'Generated by create next app',
  keywords:"web development, web design, next.js,react"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}><main className='container'>{children}</main></body>
    </html>
  )
}
